name: Test Audit
on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Dockerfile.base
      run: docker build . --file Dockerfile.base --tag jakejarvis/chrome-headless:latest
    - name: Run audit on https://github.com/
      uses: ./
      with:
        url: 'https://soundstripe-staging.netlify.app'
        auth_cookie: ${{secrets.NETLIFY_AUTH_COOKIE}}
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
